---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: naderbessioud
    password: infinidocker
    
- name: Push the Docker image into the repo
  shell: docker push naderbessioud/esprithubangular:latest
      
